#!/bin/sh

COMMIT_MSG=$1

prefix=`head -n 1 $COMMIT_MSG | awk '{ print $1 }'`
emoji=""

case $prefix in
    "init:")
        emoji=":tada:"
        ;;
    "build:")
        emoji=":building_construction:"
        ;;
    "chore:")
        emoji=":rainbow:"
        ;;
    "ci:")
        emoji=":construction_worker:"
        ;;
    "docs:")
        emoji=":memo:"
        ;;
    "feat:")
        emoji=":sparkles:"
        ;;
    "fix:")
        emoji=":bug:"
        ;;
    "perf:")
        emoji=":rocket:"
        ;;
    "refactor:")
        emoji=":art:"
        ;;
    "revert:")
        emoji=":rewind:"
        ;;
    "style:")
        emoji=":lipstick:"
        ;;
    "test:")
        emoji=":test_tube:"
        ;;
    *)
        echo "The specified prefix is undefined.";
		exit 0
		;;
esac

message="$emoji $prefix"
sed -i "s/$prefix/$message/" $COMMIT_MSG

exit 0