#!/bin/sh

COMMIT_MSG=$1

prefix=`head -n 1 $COMMIT_MSG | awk '{ print $1 }'`
emoji=""

case $prefix in
    "fix:")
        emoji=":bug:"
        ;;
    "feat:")
        emoji=":sparkles:"
        ;;
    "docs:")
        emoji=":memo:"
        ;;
    "style:")
        emoji=":lipstick:"
        ;;
    "refactor:")
        emoji=":art:"
        ;;
    "test:")
        emoji=":test_tube:"
        ;;
    "chore:")
        emoji=":rainbow:"
        ;;
    "wip:")
        emoji=":construction:"
        ;;
    *)
        echo "The specified prefix is undefined.";
		exit 0
		;;
esac

message="$emoji$prefix"
sed -i "s/$prefix/$message/" $COMMIT_MSG

exit 0